<?php
/**
 * @var $this Wsu_AdminTheme_Block_Adminhtml_System_Config_Fieldset_Hint
 */
?>
<div class="box">
    <div style="background:url('#') no-repeat left center;padding-left:55px;min-height:42px;">
        <a href="https://github.com/washingtonstateuniversity/WSUMAGE-printproducts" target="_blank" style="float:right;">
            <img src="#" alt="Fork me on GitHub" title="Fork me on GitHub" />
        </a>
        <h4><?php echo $this->helper('wsu_printproducts')->__('Wsu PrintProducts is helper for product creation that are printed products such as business cards.'); ?></h4>
        <p style="margin-bottom:0;"><?php echo $this->helper('wsu_printproducts')->__('Full overview available'); ?> <a href="<?php echo $this->escapeHtml($this->helper('wsu_printproducts')->__('#')); ?>" target="_blank"><?php echo $this->helper('wsu_printproducts')->__('here'); ?></a>.</p>
    </div>
</div>
<h2>Print Products</h2>
<p>Change option values</p>
<!-- note we will want to place a quick image of the structure here -->